use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

// Build-time driver resource collector. Walks assets/drivers-windows and
// emits a Rust module: one `pub const` per file plus a MANIFEST mapping
// relative paths to those consts, so the whole package is compiled in as
// static bytes (offline installs) and can be unpacked at runtime.
fn main() {
    println!("cargo:rerun-if-changed=assets/drivers-windows");
    let root = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("assets")
        .join("drivers-windows");
    if !root.is_dir() {
        return;
    }

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("drv_embedded.rs");
    let mut f = fs::File::create(&out).unwrap();

    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();

    let mut entries: Vec<_> = fs::read_dir(&root)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for e in &entries {
        let name = e.file_name().to_string_lossy().to_string();
        let ident = format!("DRV_{}", sanitize(&name));
        let content = fs::read(e.path()).unwrap();
        writeln!(f, "pub static {}: &[u8] = &[{}];", ident, bytes(&content)).unwrap();
    }

    writeln!(f, "pub static MANIFEST: &[(&str, &[u8])] = &[").unwrap();
    for e in &entries {
        let name = e.file_name().to_string_lossy().to_string();
        let ident = format!("DRV_{}", sanitize(&name));
        writeln!(f, "    (\"{}\", {}),", name, ident).unwrap();
    }
    writeln!(f, "];").unwrap();
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn bytes(data: &[u8]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for chunk in data.chunks(16) {
        let s: Vec<String> = chunk.iter().map(|b| format!("{:#04x}", b)).collect();
        parts.push(s.join(","));
    }
    parts.join(",")
}