use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

// Build-time driver resource collector. Walks assets/drivers-windows and
// assets/drivers-macos and emits a Rust module: one `pub const` per file
// plus two MANIFEST tables (mac + win) mapping relative paths to those
// consts, so the whole package is compiled in as static bytes (offline
// installs) and can be unpacked at runtime.
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("drv_embedded.rs");
    let mut f = fs::File::create(&out).unwrap();
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();

    // Windows: INF driver package. Kept as `MANIFEST` for driver.rs compat.
    let win_root = Path::new(&manifest_dir).join("assets/drivers-windows");
    println!("cargo:rerun-if-changed=assets/drivers-windows");
    if win_root.is_dir() {
        if let Err(e) = collect(&mut f, &win_root, "DRV_WIN", "MANIFEST") {
            panic!("collect win drivers: {e}");
        }
    } else {
        writeln!(f, "pub static MANIFEST: &[(&str, &[u8])] = &[];").unwrap();
    }

    // macOS: FUJIFILM filter + PDE plugins referenced by the PPD.
    let mac_root = Path::new(&manifest_dir).join("assets/drivers-macos");
    println!("cargo:rerun-if-changed=assets/drivers-macos");
    if mac_root.is_dir() {
        if let Err(e) = collect(&mut f, &mac_root, "DRV_MAC", "MAC_MANIFEST") {
            panic!("collect mac drivers: {e}");
        }
    } else {
        writeln!(f, "pub static MAC_MANIFEST: &[(&str, &[u8])] = &[];").unwrap();
    }
}

fn collect(
    f: &mut fs::File,
    root: &Path,
    prefix: &str,
    manifest_name: &str,
) -> std::io::Result<()> {
    // Walk recursively so plugin bundles (Contents/...) keep their layout.
    let mut entries: Vec<(String, Vec<u8>)> = Vec::new();
    walk(root, root, &mut entries)?;
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    for (i, (_rel, content)) in entries.iter().enumerate() {
        let ident = format!("{}_{}", prefix, i);
        writeln!(f, "pub static {}: &[u8] = &[{}];", ident, bytes(content)).unwrap();
    }
    writeln!(
        f,
        "pub static {}: &[(&str, &[u8])] = &[",
        manifest_name
    )
    .unwrap();
    for (i, (rel, _)) in entries.iter().enumerate() {
        let ident = format!("{}_{}", prefix, i);
        writeln!(f, "    (\"{}\", {}),", rel, ident).unwrap();
    }
    writeln!(f, "];").unwrap();
    Ok(())
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<(String, Vec<u8>)>) -> std::io::Result<()> {
    for e in fs::read_dir(dir)? {
        let e = e?;
        let p = e.path();
        if p.is_dir() {
            walk(base, &p, out)?;
        } else if p.is_file() {
            let rel = p
                .strip_prefix(base)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            let content = fs::read(&p)?;
            out.push((rel, content));
        }
    }
    Ok(())
}

fn bytes(data: &[u8]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for chunk in data.chunks(16) {
        let s: Vec<String> = chunk.iter().map(|b| format!("{:#04x}", b)).collect();
        parts.push(s.join(","));
    }
    parts.join(",")
}
