use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

// Build-time driver resource collector. Walks assets/drivers-windows and
// assets/drivers-macos and emits a Rust module: one `pub const` per file
// plus two MANIFEST tables (mac + win) mapping relative paths to those
// consts, so the whole package is compiled in as static bytes (offline
// installs) and can be unpacked at runtime.
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("drv_embedded.rs");
    let mut f = fs::File::create(&out).unwrap();
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();

    // Windows: INF driver package. Kept as `MANIFEST` for driver.rs compat.
    let win_root = Path::new(&manifest_dir).join("assets/drivers-windows");
    println!("cargo:rerun-if-changed=assets/drivers-windows");
    if win_root.is_dir() {
        if let Err(e) = collect(&mut f, &win_root, "DRV_WIN", "MANIFEST") {
            panic!("collect win drivers: {e}");
        }
    } else {
        writeln!(f, "pub static MANIFEST: &[(&str, &[u8])] = &[];").unwrap();
    }

    // macOS: FUJIFILM filter + PDE plugins referenced by the PPD.
    let mac_root = Path::new(&manifest_dir).join("assets/drivers-macos");
    println!("cargo:rerun-if-changed=assets/drivers-macos");
    if mac_root.is_dir() {
        if let Err(e) = collect(&mut f, &mac_root, "DRV_MAC", "MAC_MANIFEST") {
            panic!("collect mac drivers: {e}");
        }
    } else {
        writeln!(f, "pub static MAC_MANIFEST: &[(&str, &[u8])] = &[];").unwrap();
    }
}

fn collect(
    f: &mut fs::File,
    root: &Path,
    prefix: &str,
    manifest_name: &str,
) -> std::io::Result<()> {
    // Walk recursively so plugin bundles (Contents/...) keep their layout.
    let mut entries: Vec<(String, Vec<u8>)> = Vec::new();
    walk(root, root, &mut entries)?;
    // Windows driver package: pre-expand makecab-compressed (_. / MSCF)
    // files at build time so installs don't pay extrac32 cost on every run.
    // Only on a Windows build host (extrac32 available); otherwise the
    // compressed files are embedded as-is and expanded at runtime.
    #[cfg(windows)]
    let mut entries = if manifest_name == "MANIFEST" {
        pre_expand_windows_drivers(entries)
    } else {
        entries
    };
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    for (i, (_rel, content)) in entries.iter().enumerate() {
        let ident = format!("{}_{}", prefix, i);
        writeln!(f, "pub static {}: &[u8] = &[{}];", ident, bytes(content)).unwrap();
    }
    writeln!(
        f,
        "pub static {}: &[(&str, &[u8])] = &[",
        manifest_name
    )
    .unwrap();
    for (i, (rel, _)) in entries.iter().enumerate() {
        let ident = format!("{}_{}", prefix, i);
        writeln!(f, "    (\"{}\", {}),", rel, ident).unwrap();
    }
    writeln!(f, "];").unwrap();
    Ok(())
}

/// Pre-expand makecab-compressed Windows driver files (_. suffix, MSCF
/// magic) via the system Cabinet Extraction Tool, so the embedded package
/// already contains the expanded names the INF references. Entries that fail
/// to expand are kept as-is (runtime expand_compressed handles them).
#[cfg(windows)]
fn pre_expand_windows_drivers(entries: Vec<(String, Vec<u8>)>) -> Vec<(String, Vec<u8>)> {
    use std::process::Command;
    let staging = std::env::temp_dir().join(format!("drv-pre-expand-{}", std::process::id()));
    let _ = fs::create_dir_all(&staging);
    let mut out: Vec<(String, Vec<u8>)> = Vec::with_capacity(entries.len());
    for (rel, data) in entries {
        let compressed = rel
            .rsplit('.')
            .next()
            .map(|e| e.ends_with('_'))
            .unwrap_or(false)
            && data.len() >= 4
            && &data[..4] == b"MSCF";
        if !compressed {
            out.push((rel, data));
            continue;
        }
        let tag = out.len();
        let src = staging.join(format!("src_{tag}"));
        let dest_dir = staging.join(format!("out_{tag}"));
        let expanded: Option<(String, Vec<u8>)> = (|| {
            fs::create_dir_all(&dest_dir).ok()?;
            fs::write(&src, &data).ok()?;
            let st = Command::new("extrac32.exe")
                .args(["/Y", "/E"])
                .arg(&src)
                .args(["/L"])
                .arg(&dest_dir)
                .output()
                .ok()?;
            if !st.status.success() {
                return None;
            }
            let mut rd = fs::read_dir(&dest_dir).ok()?;
            let ent = rd.next()?.ok()?;
            let bytes = fs::read(ent.path()).ok()?;
            let fname = ent.file_name().to_string_lossy().to_string();
            let parent = rel.rsplit_once('/').map(|(p, _)| p).unwrap_or("");
            let new_rel = if parent.is_empty() {
                fname
            } else {
                format!("{parent}/{fname}")
            };
            Some((new_rel, bytes))
        })();
        match expanded {
            Some((nr, nb)) => out.push((nr, nb)),
            None => out.push((rel, data)),
        }
    }
    let _ = fs::remove_dir_all(&staging);
    out
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<(String, Vec<u8>)>) -> std::io::Result<()> {
    for e in fs::read_dir(dir)? {
        let e = e?;
        let p = e.path();
        if p.is_dir() {
            walk(base, &p, out)?;
        } else if p.is_file() {
            let rel = p
                .strip_prefix(base)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            let content = fs::read(&p)?;
            out.push((rel, content));
        }
    }
    Ok(())
}

fn bytes(data: &[u8]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for chunk in data.chunks(16) {
        let s: Vec<String> = chunk.iter().map(|b| format!("{:#04x}", b)).collect();
        parts.push(s.join(","));
    }
    parts.join(",")
}
