[General Setting]
SUPPORT_NUM=2
SUPPORT_0=ApeosPrint C3060 S
SUPPORT_1=ApeosPrint C3560 S

[ApeosPrint C3060 S]
FullModelName=FUJIFILM ApeosPrint C3060 S
DefaultName=FUJIFILM ApeosPrint C3060 S
PDL=ART_EX

[ApeosPrint C3560 S]
FullModelName=FUJIFILM ApeosPrint C3560 S
DefaultName=FUJIFILM ApeosPrint C3560 S
PDL=ART_EX,PS_H2,PS_J2

[Setting]
MODEL_NAME_NUM=2
MODEL_NAME_0=ApeosPrint C3060 S
MODEL_NAME_1=ApeosPrint C3560 S
Printer=0,1
0=FUJIFILM ApeosPrint C3060 S
1=FUJIFILM ApeosPrint C3560 S

[Net Prn Search]
SYSOBJECTID_NUM=2
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.25.2."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.25.1."

[USB Prn Search]
USB_ID_NUM=2
USB_ID_0=""FUJIFILM ApeosPrint C3060 S""
USB_ID_1=""FUJIFILM ApeosPrint C3560 S""

LOCATION_INFO_NUM=2
LOCATION_INFO_0="ApeosPrint C3060 S"
LOCATION_INFO_1="ApeosPrint C3560 S"

[FUJIFILM ApeosPrint C3060 S]
PDL=ART_EX
ART_EX=FF ApeosPrint C3060 S
ART_EXx863INF=FFE3MPLWJ.INF
ART_EXx643INF=FFE3MPLWJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.25.2.
WSD_PRINTERNAME=FUJIFILM ApeosPrint C3060 S
USB_ID=""FUJIFILM ApeosPrint C3060 S""
PrnICMName=FFE3MPLWZA.ICM

[FUJIFILM ApeosPrint C3560 S]
PDL=ART_EX,PS_H2,PS_J2
ART_EX=FF ApeosPrint C3560 S
PS_H2=FF ApeosPrint C3560 S PS H2
PS_J2=FF ApeosPrint C3560 S PS J2
ART_EXx863INF=FFE3MPLWJ.INF
ART_EXx643INF=FFE3MPLWJ.INF
PS_H2x863INF=FFE3MPSJ.INF
PS_H2x643INF=FFE3MPSJ.INF
PS_J2x863INF=FFE3MPSJ.INF
PS_J2x643INF=FFE3MPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.25.1.
WSD_PRINTERNAME=FUJIFILM ApeosPrint C3560 S
USB_ID=""FUJIFILM ApeosPrint C3560 S""
PrnICMName=FFE3MPLWZB.ICM


;[WSD] stands for [Web Services on Devices].
