[General Setting]
SUPPORT_NUM=3
SUPPORT_0=ApeosPro C650
SUPPORT_1=ApeosPro C750
SUPPORT_2=ApeosPro C810

[ApeosPro C650]
FullModelName=FUJIFILM ApeosPro C650
DefaultName=FUJIFILM ApeosPro C650
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[ApeosPro C750]
FullModelName=FUJIFILM ApeosPro C750
DefaultName=FUJIFILM ApeosPro C750
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[ApeosPro C810]
FullModelName=FUJIFILM ApeosPro C810
DefaultName=FUJIFILM ApeosPro C810
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[Setting]
MODEL_NAME_NUM=3
MODEL_NAME_0=ApeosPro C650
MODEL_NAME_1=ApeosPro C750
MODEL_NAME_2=ApeosPro C810
Printer=0,1,2
0=FUJIFILM ApeosPro C650
1=FUJIFILM ApeosPro C750
2=FUJIFILM ApeosPro C810

[Net Prn Search]
SYSOBJECTID_NUM=3
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.3.2."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.3.4."
SYSOBJECTID_2="1.3.6.1.4.1.297.1.11.93.2.1.3.6."

[USB Prn Search]
USB_ID_NUM=3
USB_ID_0=""FUJIFILM ApeosPro C650""
USB_ID_1=""FUJIFILM ApeosPro C750""
USB_ID_2=""FUJIFILM ApeosPro C810""

LOCATION_INFO_NUM=3
LOCATION_INFO_0="ApeosPro C650"
LOCATION_INFO_1="ApeosPro C750"
LOCATION_INFO_2="ApeosPro C810"

[FUJIFILM ApeosPro C650]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF ApeosPro C650
PS_H2=FF ApeosPro C650 PS H2
PS_J2=FF ApeosPro C650 PS J2
PS_J5=FF ApeosPro C650 PS J5
ART_EXx863INF=FFGRFPLWJ.INF
ART_EXx643INF=FFGRFPLWJ.INF
PS_H2x863INF=FFGRFPSJ.INF
PS_H2x643INF=FFGRFPSJ.INF
PS_J2x863INF=FFGRFPSJ.INF
PS_J2x643INF=FFGRFPSJ.INF
PS_J5x863INF=FFGRFPSJ.INF
PS_J5x643INF=FFGRFPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.3.2.
WSD_PRINTERNAME=FUJIFILM ApeosPro C650
USB_ID=""FUJIFILM ApeosPro C650""
PrnICMName=FFGRFPLWZA.ICM

[FUJIFILM ApeosPro C750]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF ApeosPro C750
PS_H2=FF ApeosPro C750 PS H2
PS_J2=FF ApeosPro C750 PS J2
PS_J5=FF ApeosPro C750 PS J5
ART_EXx863INF=FFGRFPLWJ.INF
ART_EXx643INF=FFGRFPLWJ.INF
PS_H2x863INF=FFGRFPSJ.INF
PS_H2x643INF=FFGRFPSJ.INF
PS_J2x863INF=FFGRFPSJ.INF
PS_J2x643INF=FFGRFPSJ.INF
PS_J5x863INF=FFGRFPSJ.INF
PS_J5x643INF=FFGRFPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.3.4.
WSD_PRINTERNAME=FUJIFILM ApeosPro C750
USB_ID=""FUJIFILM ApeosPro C750""
PrnICMName=FFGRFPLWZB.ICM

[FUJIFILM ApeosPro C810]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF ApeosPro C810
PS_H2=FF ApeosPro C810 PS H2
PS_J2=FF ApeosPro C810 PS J2
PS_J5=FF ApeosPro C810 PS J5
ART_EXx863INF=FFGRFPLWJ.INF
ART_EXx643INF=FFGRFPLWJ.INF
PS_H2x863INF=FFGRFPSJ.INF
PS_H2x643INF=FFGRFPSJ.INF
PS_J2x863INF=FFGRFPSJ.INF
PS_J2x643INF=FFGRFPSJ.INF
PS_J5x863INF=FFGRFPSJ.INF
PS_J5x643INF=FFGRFPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.3.6.
WSD_PRINTERNAME=FUJIFILM ApeosPro C810
USB_ID=""FUJIFILM ApeosPro C810""
PrnICMName=FFGRFPLWZC.ICM


;[WSD] stands for [Web Services on Devices].
