[General Setting]
SUPPORT_NUM=2
SUPPORT_0=ApeosPrint C4570
SUPPORT_1=ApeosPrint C5570

[ApeosPrint C4570]
FullModelName=FUJIFILM ApeosPrint C4570
DefaultName=FUJIFILM ApeosPrint C4570
PDL=ART_EX,PS_H2,PS_J2

[ApeosPrint C5570]
FullModelName=FUJIFILM ApeosPrint C5570
DefaultName=FUJIFILM ApeosPrint C5570
PDL=ART_EX,PS_H2,PS_J2

[Setting]
MODEL_NAME_NUM=2
MODEL_NAME_0=ApeosPrint C4570
MODEL_NAME_1=ApeosPrint C5570
Printer=0,1
0=FUJIFILM ApeosPrint C4570
1=FUJIFILM ApeosPrint C5570

[Net Prn Search]
SYSOBJECTID_NUM=2
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.15.1."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.15.2."

[USB Prn Search]
USB_ID_NUM=2
USB_ID_0=""FUJIFILM ApeosPrint C4570""
USB_ID_1=""FUJIFILM ApeosPrint C5570""

LOCATION_INFO_NUM=2
LOCATION_INFO_0="ApeosPrint C4570"
LOCATION_INFO_1="ApeosPrint C5570"

[FUJIFILM ApeosPrint C4570]
PDL=ART_EX,PS_H2,PS_J2
ART_EX=FF ApeosPrint C4570
PS_H2=FF ApeosPrint C4570 PS H2
PS_J2=FF ApeosPrint C4570 PS J2
ART_EXx863INF=FFKRCPLWJ.INF
ART_EXx643INF=FFKRCPLWJ.INF
PS_H2x863INF=FFKRCPSJ.INF
PS_H2x643INF=FFKRCPSJ.INF
PS_J2x863INF=FFKRCPSJ.INF
PS_J2x643INF=FFKRCPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.15.1.
WSD_PRINTERNAME=FUJIFILM ApeosPrint C4570
USB_ID=""FUJIFILM ApeosPrint C4570""
PrnICMName=FFKRCPLWZA.ICM

[FUJIFILM ApeosPrint C5570]
PDL=ART_EX,PS_H2,PS_J2
ART_EX=FF ApeosPrint C5570
PS_H2=FF ApeosPrint C5570 PS H2
PS_J2=FF ApeosPrint C5570 PS J2
ART_EXx863INF=FFKRCPLWJ.INF
ART_EXx643INF=FFKRCPLWJ.INF
PS_H2x863INF=FFKRCPSJ.INF
PS_H2x643INF=FFKRCPSJ.INF
PS_J2x863INF=FFKRCPSJ.INF
PS_J2x643INF=FFKRCPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.15.2.
WSD_PRINTERNAME=FUJIFILM ApeosPrint C5570
USB_ID=""FUJIFILM ApeosPrint C5570""
PrnICMName=FFKRCPLWZB.ICM


;[WSD] stands for [Web Services on Devices].
