[General Setting]
SUPPORT_NUM=2
SUPPORT_0=Apeos C3530
SUPPORT_1=Apeos C4030

[Apeos C3530]
FullModelName=FUJIFILM Apeos C3530
DefaultName=FUJIFILM Apeos C3530
PDL=ART_EX,PS_H2,PS_J2

[Apeos C4030]
FullModelName=FUJIFILM Apeos C4030
DefaultName=FUJIFILM Apeos C4030
PDL=ART_EX,PS_H2,PS_J2

[Setting]
MODEL_NAME_NUM=2
MODEL_NAME_0=Apeos C3530
MODEL_NAME_1=Apeos C4030
Printer=0,1
0=FUJIFILM Apeos C3530
1=FUJIFILM Apeos C4030

[Net Prn Search]
SYSOBJECTID_NUM=2
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.17.2."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.17.1."

[USB Prn Search]
USB_ID_NUM=2
USB_ID_0=""FUJIFILM Apeos C3530""
USB_ID_1=""FUJIFILM Apeos C4030""

LOCATION_INFO_NUM=2
LOCATION_INFO_0="Apeos C3530"
LOCATION_INFO_1="Apeos C4030"

[FUJIFILM Apeos C3530]
PDL=ART_EX,PS_H2,PS_J2
ART_EX=FF Apeos C3530
PS_H2=FF Apeos C3530 PS H2
PS_J2=FF Apeos C3530 PS J2
ART_EXx863INF=FFL2MPLWJ.INF
ART_EXx643INF=FFL2MPLWJ.INF
PS_H2x863INF=FFL2MPSJ.INF
PS_H2x643INF=FFL2MPSJ.INF
PS_J2x863INF=FFL2MPSJ.INF
PS_J2x643INF=FFL2MPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.17.2.
WSD_PRINTERNAME=FUJIFILM Apeos C3530
USB_ID=""FUJIFILM Apeos C3530""
PrnICMName=FFL2MPLWZA.ICM

[FUJIFILM Apeos C4030]
PDL=ART_EX,PS_H2,PS_J2
ART_EX=FF Apeos C4030
PS_H2=FF Apeos C4030 PS H2
PS_J2=FF Apeos C4030 PS J2
ART_EXx863INF=FFL2MPLWJ.INF
ART_EXx643INF=FFL2MPLWJ.INF
PS_H2x863INF=FFL2MPSJ.INF
PS_H2x643INF=FFL2MPSJ.INF
PS_J2x863INF=FFL2MPSJ.INF
PS_J2x643INF=FFL2MPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.17.1.
WSD_PRINTERNAME=FUJIFILM Apeos C4030
USB_ID=""FUJIFILM Apeos C4030""
PrnICMName=FFL2MPLWZB.ICM


;[WSD] stands for [Web Services on Devices].
