[General Setting]
SUPPORT_NUM=2
SUPPORT_0=Apeos C2060
SUPPORT_1=Apeos C2360

[Apeos C2060]
FullModelName=FUJIFILM Apeos C2060
DefaultName=FUJIFILM Apeos C2060
PDL=ART_EX,PS_H2

[Apeos C2360]
FullModelName=FUJIFILM Apeos C2360
DefaultName=FUJIFILM Apeos C2360
PDL=ART_EX,PS_H2

[Setting]
MODEL_NAME_NUM=2
MODEL_NAME_0=Apeos C2060
MODEL_NAME_1=Apeos C2360
Printer=0,1
0=FUJIFILM Apeos C2060
1=FUJIFILM Apeos C2360

[Net Prn Search]
SYSOBJECTID_NUM=2
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.11.1."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.11.2."

[USB Prn Search]
USB_ID_NUM=2
USB_ID_0=""FUJIFILM Apeos C2060""
USB_ID_1=""FUJIFILM Apeos C2360""

LOCATION_INFO_NUM=2
LOCATION_INFO_0="Apeos C2060"
LOCATION_INFO_1="Apeos C2360"

[FUJIFILM Apeos C2060]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C2060
PS_H2=FF Apeos C2060 PS H2
ART_EXx863INF=FFMA4PLWJ.INF
ART_EXx643INF=FFMA4PLWJ.INF
PS_H2x863INF=FFMA4PSJ.INF
PS_H2x643INF=FFMA4PSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.11.1.
WSD_PRINTERNAME=FUJIFILM Apeos C2060
USB_ID=""FUJIFILM Apeos C2060""
PrnICMName=FFMA4PLWZA.ICM

[FUJIFILM Apeos C2360]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C2360
PS_H2=FF Apeos C2360 PS H2
ART_EXx863INF=FFMA4PLWJ.INF
ART_EXx643INF=FFMA4PLWJ.INF
PS_H2x863INF=FFMA4PSJ.INF
PS_H2x643INF=FFMA4PSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.11.2.
WSD_PRINTERNAME=FUJIFILM Apeos C2360
USB_ID=""FUJIFILM Apeos C2360""
PrnICMName=FFMA4PLWZB.ICM


;[WSD] stands for [Web Services on Devices].
