[General Setting]
SUPPORT_NUM=3
SUPPORT_0=Apeos 1860
SUPPORT_1=Apeos 2560
SUPPORT_2=Apeos 3060

[Apeos 1860]
FullModelName=FUJIFILM Apeos 1860
DefaultName=FUJIFILM Apeos 1860
PDL=ART_EX,PS_H2

[Apeos 2560]
FullModelName=FUJIFILM Apeos 2560
DefaultName=FUJIFILM Apeos 2560
PDL=ART_EX,PS_H2

[Apeos 3060]
FullModelName=FUJIFILM Apeos 3060
DefaultName=FUJIFILM Apeos 3060
PDL=ART_EX,PS_H2

[Setting]
MODEL_NAME_NUM=3
MODEL_NAME_0=Apeos 1860
MODEL_NAME_1=Apeos 2560
MODEL_NAME_2=Apeos 3060
Printer=0,1,2
0=FUJIFILM Apeos 1860
1=FUJIFILM Apeos 2560
2=FUJIFILM Apeos 3060

[Net Prn Search]
SYSOBJECTID_NUM=3
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.12.1."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.12.2."
SYSOBJECTID_2="1.3.6.1.4.1.297.1.11.93.2.1.12.3."

[USB Prn Search]
USB_ID_NUM=3
USB_ID_0=""FUJIFILM Apeos 1860""
USB_ID_1=""FUJIFILM Apeos 2560""
USB_ID_2=""FUJIFILM Apeos 3060""

LOCATION_INFO_NUM=3
LOCATION_INFO_0="Apeos 1860"
LOCATION_INFO_1="Apeos 2560"
LOCATION_INFO_2="Apeos 3060"

[FUJIFILM Apeos 1860]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos 1860
PS_H2=FF Apeos 1860 PS H2
ART_EXx863INF=FFMO3PLWJ.INF
ART_EXx643INF=FFMO3PLWJ.INF
PS_H2x863INF=FFMO3PSJ.INF
PS_H2x643INF=FFMO3PSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.12.1.
WSD_PRINTERNAME=FUJIFILM Apeos 1860
USB_ID=""FUJIFILM Apeos 1860""
PrnICMName=NoICCProfile

[FUJIFILM Apeos 2560]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos 2560
PS_H2=FF Apeos 2560 PS H2
ART_EXx863INF=FFMO3PLWJ.INF
ART_EXx643INF=FFMO3PLWJ.INF
PS_H2x863INF=FFMO3PSJ.INF
PS_H2x643INF=FFMO3PSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.12.2.
WSD_PRINTERNAME=FUJIFILM Apeos 2560
USB_ID=""FUJIFILM Apeos 2560""
PrnICMName=NoICCProfile

[FUJIFILM Apeos 3060]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos 3060
PS_H2=FF Apeos 3060 PS H2
ART_EXx863INF=FFMO3PLWJ.INF
ART_EXx643INF=FFMO3PLWJ.INF
PS_H2x863INF=FFMO3PSJ.INF
PS_H2x643INF=FFMO3PSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.12.3.
WSD_PRINTERNAME=FUJIFILM Apeos 3060
USB_ID=""FUJIFILM Apeos 3060""
PrnICMName=NoICCProfile


;[WSD] stands for [Web Services on Devices].
