[General Setting]
SUPPORT_NUM=1
SUPPORT_0=ApeosPrint 4830 JM

[ApeosPrint 4830 JM]
FullModelName=FUJIFILM ApeosPrint 4830 JM
DefaultName=FUJIFILM ApeosPrint 4830 JM
PDL=ART_EX

[Setting]
MODEL_NAME_NUM=1
MODEL_NAME_0=ApeosPrint 4830 JM
Printer=0
0=FUJIFILM ApeosPrint 4830 JM

[Net Prn Search]
SYSOBJECTID_NUM=1
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.20.2."

[USB Prn Search]
USB_ID_NUM=1
USB_ID_0=""FUJIFILM ApeosPrint 4830 JM""

LOCATION_INFO_NUM=1
LOCATION_INFO_0="ApeosPrint 4830 JM"

[FUJIFILM ApeosPrint 4830 JM]
PDL=ART_EX
ART_EX=FF ApeosPrint 4830 JM
ART_EXx863INF=FFN2KPLWJ.INF
ART_EXx643INF=FFN2KPLWJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.20.2.
WSD_PRINTERNAME=FUJIFILM ApeosPrint 4830 JM
USB_ID=""FUJIFILM ApeosPrint 4830 JM""
PrnICMName=NoICCProfile


;[WSD] stands for [Web Services on Devices].
