[General Setting]
SUPPORT_NUM=1
SUPPORT_0=ApeosPrint 4830

[ApeosPrint 4830]
FullModelName=FUJIFILM ApeosPrint 4830
DefaultName=FUJIFILM ApeosPrint 4830
PDL=ART_EX,PS_H3,PS_J2

[Setting]
MODEL_NAME_NUM=1
MODEL_NAME_0=ApeosPrint 4830
Printer=0
0=FUJIFILM ApeosPrint 4830

[Net Prn Search]
SYSOBJECTID_NUM=1
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.20.1."

[USB Prn Search]
USB_ID_NUM=1
USB_ID_0=""FUJIFILM ApeosPrint 4830""

LOCATION_INFO_NUM=1
LOCATION_INFO_0="ApeosPrint 4830"

[FUJIFILM ApeosPrint 4830]
PDL=ART_EX,PS_H3,PS_J2
ART_EX=FF ApeosPrint 4830
PS_H3=FF ApeosPrint 4830 PS H3
PS_J2=FF ApeosPrint 4830 PS J2
ART_EXx863INF=FFN2SPLWJ.INF
ART_EXx643INF=FFN2SPLWJ.INF
PS_H3x863INF=FFN2SPSJ.INF
PS_H3x643INF=FFN2SPSJ.INF
PS_J2x863INF=FFN2SPSJ.INF
PS_J2x643INF=FFN2SPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.20.1.
WSD_PRINTERNAME=FUJIFILM ApeosPrint 4830
USB_ID=""FUJIFILM ApeosPrint 4830""
PrnICMName=NoICCProfile


;[WSD] stands for [Web Services on Devices].
