[General Setting]
SUPPORT_NUM=3
SUPPORT_0=Apeos C6580
SUPPORT_1=Apeos C7580
SUPPORT_2=Apeos C8180

[Apeos C6580]
FullModelName=FUJIFILM Apeos C6580
DefaultName=FUJIFILM Apeos C6580
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[Apeos C7580]
FullModelName=FUJIFILM Apeos C7580
DefaultName=FUJIFILM Apeos C7580
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[Apeos C8180]
FullModelName=FUJIFILM Apeos C8180
DefaultName=FUJIFILM Apeos C8180
PDL=ART_EX,PS_H2,PS_J2,PS_J5

[Setting]
MODEL_NAME_NUM=3
MODEL_NAME_0=Apeos C6580
MODEL_NAME_1=Apeos C7580
MODEL_NAME_2=Apeos C8180
Printer=0,1,2
0=FUJIFILM Apeos C6580
1=FUJIFILM Apeos C7580
2=FUJIFILM Apeos C8180

[Net Prn Search]
SYSOBJECTID_NUM=3
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.2.2."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.2.4."
SYSOBJECTID_2="1.3.6.1.4.1.297.1.11.93.2.1.2.6."

[USB Prn Search]
USB_ID_NUM=3
USB_ID_0=""FUJIFILM Apeos C6580""
USB_ID_1=""FUJIFILM Apeos C7580""
USB_ID_2=""FUJIFILM Apeos C8180""

LOCATION_INFO_NUM=3
LOCATION_INFO_0="Apeos C6580"
LOCATION_INFO_1="Apeos C7580"
LOCATION_INFO_2="Apeos C8180"

[FUJIFILM Apeos C6580]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF Apeos C6580
PS_H2=FF Apeos C6580 PS H2
PS_J2=FF Apeos C6580 PS J2
PS_J5=FF Apeos C6580 PS J5
ART_EXx863INF=FFREKPLWJ.INF
ART_EXx643INF=FFREKPLWJ.INF
PS_H2x863INF=FFREKPSJ.INF
PS_H2x643INF=FFREKPSJ.INF
PS_J2x863INF=FFREKPSJ.INF
PS_J2x643INF=FFREKPSJ.INF
PS_J5x863INF=FFREKPSJ.INF
PS_J5x643INF=FFREKPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.2.2.
WSD_PRINTERNAME=FUJIFILM Apeos C6580
USB_ID=""FUJIFILM Apeos C6580""
PrnICMName=FFREKPLWZA.ICM

[FUJIFILM Apeos C7580]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF Apeos C7580
PS_H2=FF Apeos C7580 PS H2
PS_J2=FF Apeos C7580 PS J2
PS_J5=FF Apeos C7580 PS J5
ART_EXx863INF=FFREKPLWJ.INF
ART_EXx643INF=FFREKPLWJ.INF
PS_H2x863INF=FFREKPSJ.INF
PS_H2x643INF=FFREKPSJ.INF
PS_J2x863INF=FFREKPSJ.INF
PS_J2x643INF=FFREKPSJ.INF
PS_J5x863INF=FFREKPSJ.INF
PS_J5x643INF=FFREKPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.2.4.
WSD_PRINTERNAME=FUJIFILM Apeos C7580
USB_ID=""FUJIFILM Apeos C7580""
PrnICMName=FFREKPLWZB.ICM

[FUJIFILM Apeos C8180]
PDL=ART_EX,PS_H2,PS_J2,PS_J5
ART_EX=FF Apeos C8180
PS_H2=FF Apeos C8180 PS H2
PS_J2=FF Apeos C8180 PS J2
PS_J5=FF Apeos C8180 PS J5
ART_EXx863INF=FFREKPLWJ.INF
ART_EXx643INF=FFREKPLWJ.INF
PS_H2x863INF=FFREKPSJ.INF
PS_H2x643INF=FFREKPSJ.INF
PS_J2x863INF=FFREKPSJ.INF
PS_J2x643INF=FFREKPSJ.INF
PS_J5x863INF=FFREKPSJ.INF
PS_J5x643INF=FFREKPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.2.6.
WSD_PRINTERNAME=FUJIFILM Apeos C8180
USB_ID=""FUJIFILM Apeos C8180""
PrnICMName=FFREKPLWZC.ICM


;[WSD] stands for [Web Services on Devices].
