[General Setting]
SUPPORT_NUM=2
SUPPORT_0=Apeos 3570
SUPPORT_1=Apeos 4570

[Apeos 3570]
FullModelName=FUJIFILM Apeos 3570
DefaultName=FUJIFILM Apeos 3570
PDL=ART_EX,PS_H3,PS_J2

[Apeos 4570]
FullModelName=FUJIFILM Apeos 4570
DefaultName=FUJIFILM Apeos 4570
PDL=ART_EX,PS_H3,PS_J2

[Setting]
MODEL_NAME_NUM=2
MODEL_NAME_0=Apeos 3570
MODEL_NAME_1=Apeos 4570
Printer=0,1
0=FUJIFILM Apeos 3570
1=FUJIFILM Apeos 4570

[Net Prn Search]
SYSOBJECTID_NUM=2
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.6.1."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.6.2."

[USB Prn Search]
USB_ID_NUM=2
USB_ID_0=""FUJIFILM Apeos 3570""
USB_ID_1=""FUJIFILM Apeos 4570""

LOCATION_INFO_NUM=2
LOCATION_INFO_0="Apeos 3570"
LOCATION_INFO_1="Apeos 4570"

[FUJIFILM Apeos 3570]
PDL=ART_EX,PS_H3,PS_J2
ART_EX=FF Apeos 3570
PS_H3=FF Apeos 3570 PS H3
PS_J2=FF Apeos 3570 PS J2
ART_EXx863INF=FFSBMPLWJ.INF
ART_EXx643INF=FFSBMPLWJ.INF
PS_H3x863INF=FFSBMPSJ.INF
PS_H3x643INF=FFSBMPSJ.INF
PS_J2x863INF=FFSBMPSJ.INF
PS_J2x643INF=FFSBMPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.6.1.
WSD_PRINTERNAME=FUJIFILM Apeos 3570
USB_ID=""FUJIFILM Apeos 3570""
PrnICMName=NoICCProfile

[FUJIFILM Apeos 4570]
PDL=ART_EX,PS_H3,PS_J2
ART_EX=FF Apeos 4570
PS_H3=FF Apeos 4570 PS H3
PS_J2=FF Apeos 4570 PS J2
ART_EXx863INF=FFSBMPLWJ.INF
ART_EXx643INF=FFSBMPLWJ.INF
PS_H3x863INF=FFSBMPSJ.INF
PS_H3x643INF=FFSBMPSJ.INF
PS_J2x863INF=FFSBMPSJ.INF
PS_J2x643INF=FFSBMPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.6.2.
WSD_PRINTERNAME=FUJIFILM Apeos 4570
USB_ID=""FUJIFILM Apeos 4570""
PrnICMName=NoICCProfile


;[WSD] stands for [Web Services on Devices].
