[General Setting]
SUPPORT_NUM=3
SUPPORT_0=Apeos C2061
SUPPORT_1=Apeos C2561
SUPPORT_2=Apeos C3061

[Apeos C2061]
FullModelName=FUJIFILM Apeos C2061
DefaultName=FUJIFILM Apeos C2061
PDL=ART_EX,PS_H2

[Apeos C2561]
FullModelName=FUJIFILM Apeos C2561
DefaultName=FUJIFILM Apeos C2561
PDL=ART_EX,PS_H2

[Apeos C3061]
FullModelName=FUJIFILM Apeos C3061
DefaultName=FUJIFILM Apeos C3061
PDL=ART_EX,PS_H2

[Setting]
MODEL_NAME_NUM=3
MODEL_NAME_0=Apeos C2061
MODEL_NAME_1=Apeos C2561
MODEL_NAME_2=Apeos C3061
Printer=0,1,2
0=FUJIFILM Apeos C2061
1=FUJIFILM Apeos C2561
2=FUJIFILM Apeos C3061

[Net Prn Search]
SYSOBJECTID_NUM=3
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.31.1."
SYSOBJECTID_1="1.3.6.1.4.1.297.1.11.93.2.1.31.2."
SYSOBJECTID_2="1.3.6.1.4.1.297.1.11.93.2.1.31.3."

[USB Prn Search]
USB_ID_NUM=3
USB_ID_0=""FUJIFILM Apeos C2061""
USB_ID_1=""FUJIFILM Apeos C2561""
USB_ID_2=""FUJIFILM Apeos C3061""

LOCATION_INFO_NUM=3
LOCATION_INFO_0="Apeos C2061"
LOCATION_INFO_1="Apeos C2561"
LOCATION_INFO_2="Apeos C3061"

[FUJIFILM Apeos C2061]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C2061
PS_H2=FF Apeos C2061 PS H2
ART_EXx863INF=FFSRBPLWJ.INF
ART_EXx643INF=FFSRBPLWJ.INF
PS_H2x863INF=FFSRBPSJ.INF
PS_H2x643INF=FFSRBPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.31.1.
WSD_PRINTERNAME=FUJIFILM Apeos C2061
USB_ID=""FUJIFILM Apeos C2061""
PrnICMName=FFSRBPLWZA.ICM

[FUJIFILM Apeos C2561]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C2561
PS_H2=FF Apeos C2561 PS H2
ART_EXx863INF=FFSRBPLWJ.INF
ART_EXx643INF=FFSRBPLWJ.INF
PS_H2x863INF=FFSRBPSJ.INF
PS_H2x643INF=FFSRBPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.31.2.
WSD_PRINTERNAME=FUJIFILM Apeos C2561
USB_ID=""FUJIFILM Apeos C2561""
PrnICMName=FFSRBPLWZB.ICM

[FUJIFILM Apeos C3061]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C3061
PS_H2=FF Apeos C3061 PS H2
ART_EXx863INF=FFSRBPLWJ.INF
ART_EXx643INF=FFSRBPLWJ.INF
PS_H2x863INF=FFSRBPSJ.INF
PS_H2x643INF=FFSRBPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.31.3.
WSD_PRINTERNAME=FUJIFILM Apeos C3061
USB_ID=""FUJIFILM Apeos C3061""
PrnICMName=FFSRBPLWZC.ICM


;[WSD] stands for [Web Services on Devices].
