[General Setting]
SUPPORT_NUM=1
SUPPORT_0=Apeos C3067

[Apeos C3067]
FullModelName=FUJIFILM Apeos C3067
DefaultName=FUJIFILM Apeos C3067
PDL=ART_EX,PS_H2

[Setting]
MODEL_NAME_NUM=1
MODEL_NAME_0=Apeos C3067
Printer=0
0=FUJIFILM Apeos C3067

[Net Prn Search]
SYSOBJECTID_NUM=1
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.32.1."

[USB Prn Search]
USB_ID_NUM=1
USB_ID_0=""FUJIFILM Apeos C3067""

LOCATION_INFO_NUM=1
LOCATION_INFO_0="Apeos C3067"

[FUJIFILM Apeos C3067]
PDL=ART_EX,PS_H2
ART_EX=FF Apeos C3067
PS_H2=FF Apeos C3067 PS H2
ART_EXx863INF=FFSRAPLWJ.INF
ART_EXx643INF=FFSRAPLWJ.INF
PS_H2x863INF=FFSRAPSJ.INF
PS_H2x643INF=FFSRAPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.32.1.
WSD_PRINTERNAME=FUJIFILM Apeos C3067
USB_ID=""FUJIFILM Apeos C3067""
PrnICMName=FFSRAPLWZB.ICM


;[WSD] stands for [Web Services on Devices].
