[General Setting]
SUPPORT_NUM=1
SUPPORT_0=Apeos 6340

[Apeos 6340]
FullModelName=FUJIFILM Apeos 6340
DefaultName=FUJIFILM Apeos 6340
PDL=ART_EX,PS_H3,PS_J2

[Setting]
MODEL_NAME_NUM=1
MODEL_NAME_0=Apeos 6340
Printer=0
0=FUJIFILM Apeos 6340

[Net Prn Search]
SYSOBJECTID_NUM=1
SYSOBJECTID_0="1.3.6.1.4.1.297.1.11.93.2.1.9.1."

[USB Prn Search]
USB_ID_NUM=1
USB_ID_0=""FUJIFILM Apeos 6340""

LOCATION_INFO_NUM=1
LOCATION_INFO_0="Apeos 6340"

[FUJIFILM Apeos 6340]
PDL=ART_EX,PS_H3,PS_J2
ART_EX=FF Apeos 6340
PS_H3=FF Apeos 6340 PS H3
PS_J2=FF Apeos 6340 PS J2
ART_EXx863INF=FFV2MPLWJ.INF
ART_EXx643INF=FFV2MPLWJ.INF
PS_H3x863INF=FFV2MPSJ.INF
PS_H3x643INF=FFV2MPSJ.INF
PS_J2x863INF=FFV2MPSJ.INF
PS_J2x643INF=FFV2MPSJ.INF
OID_PRINTER=1.3.6.1.4.1.297.1.11.93.2.1.9.1.
WSD_PRINTERNAME=FUJIFILM Apeos 6340
USB_ID=""FUJIFILM Apeos 6340""
PrnICMName=NoICCProfile


;[WSD] stands for [Web Services on Devices].
