[Setting]
WebPack=1
ModelIniPath=.\Models

[ModelCommon]
ART_EXx863=..\Software\ART_EX\i386\Common\001
ART_EXx643=..\Software\ART_EX\amd64\Common\001
ART_EXx863VER=0.0.0.1
ART_EXx643VER=0.0.0.1
ART_EXSETTING=DRIVERSIDE

PS_H3x863=..\Software\PS\i386\English\001
PS_H3x643=..\Software\PS\amd64\English\001
PS_H3x863VER=0.0.0.1
PS_H3x643VER=0.0.0.1
PS_H3SETTING=DRIVERSIDE

PS_H2x863=..\Software\PS\i386\English\001
PS_H2x643=..\Software\PS\amd64\English\001
PS_H2x863VER=0.0.0.1
PS_H2x643VER=0.0.0.1
PS_H2SETTING=DRIVERSIDE

PS_J2x863=..\Software\PS\i386\English\001
PS_J2x643=..\Software\PS\amd64\English\001
PS_J2x863VER=0.0.0.1
PS_J2x643VER=0.0.0.1
PS_J2SETTING=DRIVERSIDE

PS_J5x863=..\Software\PS\i386\English\001
PS_J5x643=..\Software\PS\amd64\English\001
PS_J5x863VER=0.0.0.1
PS_J5x643VER=0.0.0.1
PS_J5SETTING=DRIVERSIDE

WSD_SEARCH_TIMEOUT=180000

FaxICMName=NoICCProfile
DEVICE_INIT_TIMEOUT=4000

DLLPATH=BIN\ComDLL\SubDLL\FFZQNX6.DLL


[DDMIF]
DLLPATH=BIN\ComDLL\SubDLL\ffzddmif.dll

;[WSD] stands for [Web Services on Devices].
